### ISSUE TITLE
Use Entity APIs for Provenance UI

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/provenance-ui#1]
- Need to rework process to create graph by utilizing Entity APIs `/entities/<identifier>/provenance` endpoint
- The activity node needs to show the Protocol URL attribute
- Add a way to toggle showing/hiding the activities 
  - When activities are hidden entities would be directly linked to one another with the "used" relationship
- Investigate using the Neo4j graphing tool https://neo4j.com/developer/tools-graph-visualization/
- If using D3, investigate using `tree` layout rather than the `force` layout for better rendering

**Comment by libpitt** [comment]
@maxsibilla 
Was looking into 
https://neo4j.com/developer/tools-graph-visualization/ from the card investigation request. What they give us is a list of libraries from two categories we can use. Either direct connection to the neo4j db, using cypher quieries, or without direct connection. I'm not sure direct connection is what we are looking for, we can discuss more if needed. As for without direct connection, one of their recommendations is already what we are using, d3. Vis.js looks like a neat tool, yet will likely have to reformat the data to what the library expects. 
> we often must transform the results to export from Neo4j into the format expected by these libraries.
