### ISSUE TITLE
Create a standalone Provenance UI component for React

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/provenance-ui#17]
There are other groups that want to utilize the Provenance UI in a more convenient way so we should look into publishing this library as a component on npm.

**Comment by libpitt** [comment]
[We need a package name:](https://dev.to/backendbro/a-step-by-step-guide-how-to-create-and-publish-an-npm-package-2off)

**Comment by libpitt** [comment]
https://dev.to/backendbro/a-step-by-step-guide-how-to-create-and-publish-an-npm-package-2off

**Comment by maxsibilla** [comment]
Provenance UI is already set up to be imported as a React component so no additional work needs to be done
